# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bay_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Btype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BayAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.CharField(max_length=30)),
                ('EndTime', models.CharField(max_length=40)),
                ('Bay_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Bay_type')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_No', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActualDtime', models.CharField(max_length=30)),
                ('ActualAtime', models.CharField(max_length=40)),
                ('Date', models.DateField()),
                ('Aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Aircraft')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Flight')),
            ],
        ),
        migrations.AddField(
            model_name='bayallocation',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Schedule'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Aircraft_type'),
        ),
    ]
