# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_tag', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bay_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Btype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNo', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Arrival_time', models.CharField(max_length=10)),
                ('Departure_time', models.CharField(max_length=10)),
                ('Duration', models.CharField(max_length=20)),
                ('Aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Department')),
            ],
        ),
        migrations.AddField(
            model_name='bay',
            name='Bay_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Bay_type'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaysApp.Aircraft_type'),
        ),
    ]
