# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayallocation',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='bayallocation',
            name='FlightNo',
            field=models.CharField(default='KQ3EA', max_length=30),
        ),
        migrations.AlterField(
            model_name='bayallocation',
            name='Bay_id',
            field=models.CharField(default='1A', max_length=30),
        ),
    ]
